### ISSUE TITLE
Migrate bostrom to SQL

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox#66]
- [x] #69
- [x] #70
- [x] Add staking module tables
- [x] Add message table 
- [x] #74
- [x] Add wasm module tables 
- [x] #75
- [x] Add send table
- [x] Add multisend table
- [x] Add claim table 
- [x] #76
- [x] #71
- [x] #72

**Comment by iljagrabar14** [comment]
multisend: for first item from input. 
for each coin in outputs.coints need to create
from_address : input[1]
to_address: output addres
denom 
amount

**Comment by iljagrabar14** [comment]
claim
/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward

take data from events
for each withdraw_rewards save
validator_address: withdraw_rewards.validator
coin withdraw_rewards.coin
delegator_address: message.sender

**Comment by iljagrabar14** [comment]
run all manually
