### ISSUE TITLE
Add genesis_balances table

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox#72]
the table definition

```sql=
CREATE TABLE spacebox.genesis_balances
(
    `height` Int64,
    `type` String,
    `address` String,
    `coins` String,
    `amount` Int64,
    `denom` String
)
ENGINE = MergeTree
ORDER BY (height,
 address,
 denom)
SETTINGS index_granularity = 8192;
```

there is no writer MV for that, this is only static data to get a starting point of balances. One insert is enough

**Comment by iljagrabar14** [comment]
select * from spacebox.raw_genesis rg  (app state, balances, type= "coin_received" (like in debs and creds), height  is 0, coins not need
