### ISSUE TITLE
Neutron stage 3 

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox#78]
- [x] #80
- [x] #81
- [x] #82
- [x] #83
- [x] #79
- [x] #84
- [x] finalized block results view for debs_and_creds
- [x] #87
- [x] #88
- [x] neutron contractmanager
- [ ] #89
- [ ] neutron dynamicfees
- [ ] #90
- [x] #91
- [x] #92
- [x] neutron interchaintxs
- [x] neutron transfer
- [x] block-sdk auction
- [ ]  block-sdk mempool
- [ ] block-sdk porposals

**Comment by bro-n-bro-0** [comment]
@iljagrabar14 useful links:

https://docs.neutron.org/

https://github.com/neutron-org/neutron/tree/main/proto/neutron   tx.proto by module

https://docs.neutron.org/neutron/modules/3rdparty/skip/block-sdk/overview

https://github.com/skip-mev/block-sdk/tree/main/proto/sdk x.proto by module

**Comment by iljagrabar14** [comment]
neutron interchaintxs
 messages
MsgRegisterInterchainAccount - exists

MsgSubmitTx - not exist
