### ISSUE TITLE
Add neutron feeburner module

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox#90]
neutron1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrstdxvff

https://docs.neutron.org/neutron/modules/feeburner/overview#abstract

**Comment by iljagrabar14** [comment]
check all received transactions for this address

**Comment by iljagrabar14** [comment]
compare with this value neutron/feeburner/total_burned_neutrons_amount

**Comment by iljagrabar14** [comment]
select *, JSONExtractString(message, 'toAddress') as to_address from (
SELECT * FROM spacebox.message WHERE  type = '/cosmos.bank.v1beta1.MsgSend'
) where to_address = 'neutron1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrstdxvff'

total 93879983 untr

denom	:	factory/neutron1fjn0vr4dma5crx2rctv6vmfwxx0v0vrdk50l3p/TakumiProp16JunoWhaleInu
amount	:	420690000


denom	:	ibc/2FCBC9ECB42BBBD3A9F25E780ED03C93E62D0E414A6687A4D4A2E1EBAED48BFA
amount	:	10
