### ISSUE TITLE
Add neutron feerefunder module

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox#91]
https://docs.neutron.org/neutron/modules/feerefunder/overview

**Comment by iljagrabar14** [comment]
select * from spacebox.raw_transaction where events ILIKE '%lock_fees%' limit 1

select * from spacebox.raw_transaction where events ILIKE '%distribute_ack_fee%' limit 1


select * from spacebox.raw_transaction where events ILIKE '%distribute_timeout_fee%' limit 1
